#!/bin/bash
awk 'BEGIN{printf "%s\n", strtonum("0x"gensub(/./, sprintf("%x", index("ewatr", "&")-1), "g", ENVIRON["WATER"])) + strtonum("0x"gensub(/./, sprintf("%x", index("tir.", "&")-1), "g", ENVIRON["STIR"]))}'
